---
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/migrate/**/*'
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false
